spring.application.name=boot_react

#mariadb 설정
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/springbootdb
spring.datasource.username=gduser
spring.datasource.password=1234

#Connection Pool 설정
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.read-only=false
spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.maximum-pool-size=20

#JPA 관련 설정
#update : 엔티티클래스에 맞도록 db의 테이블을 변경하기. (개발환경)
# none  : db 테이블 변경 불가 
spring.jpa.hibernate.ddl-auto=update
#실제 실행되는 SQL 구문을 콘솔에 출력 (개발환경)
spring.jpa.show-sql=true

#fileupload 
spring.servlet.multipart.max-file-size=512MB
spring.servlet.multipart.max-request-size=512MB

board.upload.dir=D:/20251222/springboot/workspace/boot_react/src/main/resources/static/
member.upload.dir=D:/20251222/springboot/workspace/boot_react/src/main/resources/static/